env:
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:import/recommended'

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0
  no-await-in-loop: 0
  no-restricted-syntax: 0